apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-build-pipeline
spec:
  workspaces:
    - name: workspace
  params:
    - name: git_url
      description: Git url
    - name: branch
      description: Revision to use
    - name: image
    - name: tag
  tasks:
    - name: checkout
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git_url)
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      runAfter:
        - checkout
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.image):$(params.tag)
      workspaces:
       - name: source
         workspace: workspace